version: "3.7"

services:
  vscode:
    image: ghcr.io/ihabsoliman/godev:1.21-debian-v0.4.0
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      # On Linux and OSX, a symlink /mnt/ssh <-> ~/.ssh is
      # created in the container. On Windows, files are copied
      # from /mnt/ssh to ~/.ssh to fix permissions.
      - ~/.ssh:/mnt/ssh
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history
      # Git config
      - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    cap_add:
      # For debugging with dlv
      - SYS_PTRACE
    security_opt:
      # For debugging with dlv
      - seccomp:unconfined
    entrypoint: [ "zsh", "-c", "while sleep 1000; do :; done" ]

  redis:
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  redis-data:
